title: Eirini Vangeli
description: Eirini Vangeli is a visual storyteller and marketing professional based in Los Angeles. Portfolio of tour journals, merchandise design, and creative projects.
url: "https://eirvangeli.github.io"
baseurl: ""
author: Eirini Vangeli

collections:
  projects:
    output: true
    permalink: /projects/:slug/
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
